name: sparrow_ui
description: Sparrow UI Components Library for Flutter.
version: 0.6.0
homepage: https://github.com/hanguangbaihuo/sparrow_ui

environment:
  # sdk: '>=2.12.0 <3.0.0'
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  sparrow_utils: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
